apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>-<APPVERSION>
  namespace: <NAMESPACE>
spec:
  replicas: <REPLICA_NUM>
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: <APP_NAME>
      version: <APPVERSION>
  template:
    metadata:
      labels:
        app.kubernetes.io/name: <APP_NAME>
        version: <APPVERSION>
    spec:
      containers:
      - name: <APP_NAME>
        image: "<ECR_REPO_URL>:<VERSION>"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}

          # envFrom:
          #   - configMapRef:
          #       name: <CONFIGMAP_COMMON_NAME>
          #   - configMapRef:
          #       name: <CONFIGMAP_NAME>
          #          livenessProbe:
          #            httpGet:
          #              path: "/<APP_NAME>/actuator/health"
          #              port: 8080
          #              scheme: HTTP
          #            initialDelaySeconds: 10
          #            periodSeconds: 3
          #            timeoutSeconds: 5
          #          readinessProbe:
          #            httpGet:
          #              path: "/<APP_NAME>/actuator/health"
          #              port: 8080
          #              scheme: HTTP
          #            initialDelaySeconds: 10
          #            periodSeconds: 3
          #            timeoutSeconds: 5
#          resources:
#            requests:
#              memory: 1000Mi
#              cpu: 500m
#            limits:
#              memory: 1700Mi
#              cpu: 900m
